name: chopperblocpagination
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  cupertino_icons: ^0.1.2
  chopper: ^3.0.2
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  json_annotation: ^3.0.1
  equatable: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  chopper_generator:
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true

# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg



# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
